const uint16_t ALPHA = 0xFFFF;

const unsigned int playerFaceSouthBMP[16*16] = {
  ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_Black, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, TS_8b_Black, TS_8b_Red, TS_8b_Red, TS_8b_Red, TS_8b_Red, TS_8b_Red, TS_8b_Red, TS_8b_Black, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, 
  ALPHA, ALPHA, TS_8b_Black, TS_8b_Red, TS_8b_Red, TS_8b_Red, TS_8b_Red, TS_8b_Red, TS_8b_Red, TS_8b_Red, TS_8b_Red, TS_8b_Black, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, TS_8b_Black, TS_8b_Red, TS_8b_Red, TS_8b_Red, TS_8b_Red, TS_8b_Red, TS_8b_Red, TS_8b_Red, TS_8b_Red, TS_8b_Black, ALPHA, ALPHA, ALPHA, ALPHA, 
  ALPHA, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_Red, TS_8b_White, TS_8b_White, TS_8b_White, TS_8b_White, TS_8b_Red, TS_8b_Black, TS_8b_Black, TS_8b_Black, ALPHA, ALPHA, ALPHA, ALPHA, TS_8b_Black, TS_8b_Black, TS_8b_White, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_White, TS_8b_Black, TS_8b_Black, ALPHA, ALPHA, ALPHA, 
  TS_8b_Black, TS_8b_White, TS_8b_Black, TS_8b_White, TS_8b_White, TS_8b_White, TS_8b_White, TS_8b_White, TS_8b_White, TS_8b_White, TS_8b_White, TS_8b_Black, TS_8b_White, TS_8b_Black, ALPHA, ALPHA, TS_8b_Black, TS_8b_White, TS_8b_White, TS_8b_White, TS_8b_White, TS_8b_Black, TS_8b_White, TS_8b_White, TS_8b_Black, TS_8b_White, TS_8b_White, TS_8b_White, TS_8b_White, TS_8b_Black, ALPHA, ALPHA, 
  ALPHA, TS_8b_Black, TS_8b_Black, TS_8b_White, TS_8b_White, TS_8b_Black, TS_8b_White, TS_8b_White, TS_8b_Black, TS_8b_White, TS_8b_White, TS_8b_Black, TS_8b_Black, ALPHA, ALPHA, ALPHA, ALPHA, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_White, TS_8b_White, TS_8b_Red, TS_8b_Red, TS_8b_White, TS_8b_White, TS_8b_Black, TS_8b_Black, TS_8b_Black, ALPHA, ALPHA, ALPHA, 
  TS_8b_Black, TS_8b_White, TS_8b_White, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_White, TS_8b_White, TS_8b_Black, ALPHA, ALPHA, TS_8b_Black, TS_8b_White, TS_8b_White, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_White, TS_8b_White, TS_8b_Black, ALPHA, ALPHA, 
  ALPHA, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_Red, TS_8b_Red, TS_8b_Black, TS_8b_Black, TS_8b_Red, TS_8b_Red, TS_8b_Black, TS_8b_Black, TS_8b_Black, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, TS_8b_Black, TS_8b_Red, TS_8b_Black, TS_8b_Black, TS_8b_Red, TS_8b_Red, TS_8b_Black, TS_8b_Black, TS_8b_Red, TS_8b_Black, ALPHA, ALPHA, ALPHA, ALPHA, 
  ALPHA, ALPHA, TS_8b_Black, TS_8b_Red, TS_8b_Red, TS_8b_Red, TS_8b_Black, TS_8b_Black, TS_8b_Red, TS_8b_Red, TS_8b_Red, TS_8b_Black, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, TS_8b_Black, TS_8b_Black, TS_8b_Black, ALPHA, ALPHA, TS_8b_Black, TS_8b_Black, TS_8b_Black, ALPHA, ALPHA, ALPHA, ALPHA
};

const unsigned int playerWalkSouthLeftBMP[16*16] = {
  ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_Black, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, 
  ALPHA, ALPHA, ALPHA, TS_8b_Black, TS_8b_Red, TS_8b_Red, TS_8b_Red, TS_8b_Red, TS_8b_Red, TS_8b_Red, TS_8b_Black, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, TS_8b_Black, TS_8b_Red, TS_8b_Red, TS_8b_Red, TS_8b_Red, TS_8b_Red, TS_8b_Red, TS_8b_Red, TS_8b_Red, TS_8b_Black, ALPHA, ALPHA, ALPHA, ALPHA, 
  ALPHA, ALPHA, TS_8b_Black, TS_8b_Red, TS_8b_Red, TS_8b_Red, TS_8b_Red, TS_8b_Red, TS_8b_Red, TS_8b_Red, TS_8b_Red, TS_8b_Black, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_Red, TS_8b_White, TS_8b_White, TS_8b_White, TS_8b_White, TS_8b_Red, TS_8b_Black, TS_8b_Black, TS_8b_Black, ALPHA, ALPHA, ALPHA, 
  ALPHA, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_Black, ALPHA, ALPHA, ALPHA, TS_8b_Black, TS_8b_White, TS_8b_Black, TS_8b_White, TS_8b_White, TS_8b_White, TS_8b_White, TS_8b_White, TS_8b_White, TS_8b_White, TS_8b_White, TS_8b_Black, TS_8b_White, TS_8b_Black, ALPHA, ALPHA, 
  TS_8b_Black, TS_8b_White, TS_8b_White, TS_8b_White, TS_8b_White, TS_8b_Black, TS_8b_White, TS_8b_White, TS_8b_Black, TS_8b_White, TS_8b_White, TS_8b_White, TS_8b_White, TS_8b_Black, ALPHA, ALPHA, ALPHA, TS_8b_Black, TS_8b_Black, TS_8b_White, TS_8b_White, TS_8b_Black, TS_8b_White, TS_8b_White, TS_8b_Black, TS_8b_White, TS_8b_White, TS_8b_Black, TS_8b_Black, TS_8b_Black, ALPHA, ALPHA, 
  ALPHA, TS_8b_Black, TS_8b_Red, TS_8b_Black, TS_8b_White, TS_8b_White, TS_8b_Red, TS_8b_Red, TS_8b_White, TS_8b_White, TS_8b_Black, TS_8b_Black, TS_8b_White, TS_8b_Black, ALPHA, ALPHA, ALPHA, TS_8b_Black, TS_8b_White, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_Black, ALPHA, ALPHA, ALPHA, 
  ALPHA, TS_8b_Black, TS_8b_Black, TS_8b_White, TS_8b_White, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_Red, TS_8b_Black, TS_8b_Black, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, TS_8b_Black, TS_8b_White, TS_8b_White, TS_8b_Black, TS_8b_Red, TS_8b_Red, TS_8b_Black, TS_8b_Black, TS_8b_Black, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, 
  ALPHA, ALPHA, ALPHA, TS_8b_Black, TS_8b_Black, ALPHA, TS_8b_Black, TS_8b_Black, TS_8b_Red, TS_8b_Red, TS_8b_Black, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, TS_8b_Black, TS_8b_Black, TS_8b_Black, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA
};

const unsigned int playerWalkSouthRightBMP[16*16] = {
  ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_Black, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, 
  ALPHA, ALPHA, ALPHA, TS_8b_Black, TS_8b_Red, TS_8b_Red, TS_8b_Red, TS_8b_Red, TS_8b_Red, TS_8b_Red, TS_8b_Black, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, TS_8b_Black, TS_8b_Red, TS_8b_Red, TS_8b_Red, TS_8b_Red, TS_8b_Red, TS_8b_Red, TS_8b_Red, TS_8b_Red, TS_8b_Black, ALPHA, ALPHA, ALPHA, ALPHA, 
  ALPHA, ALPHA, TS_8b_Black, TS_8b_Red, TS_8b_Red, TS_8b_Red, TS_8b_Red, TS_8b_Red, TS_8b_Red, TS_8b_Red, TS_8b_Red, TS_8b_Black, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_Red, TS_8b_White, TS_8b_White, TS_8b_White, TS_8b_White, TS_8b_Red, TS_8b_Black, TS_8b_Black, TS_8b_Black, ALPHA, ALPHA, ALPHA, 
  ALPHA, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_Black, ALPHA, ALPHA, ALPHA, TS_8b_Black, TS_8b_White, TS_8b_Black, TS_8b_White, TS_8b_White, TS_8b_White, TS_8b_White, TS_8b_White, TS_8b_White, TS_8b_White, TS_8b_White, TS_8b_Black, TS_8b_White, TS_8b_Black, ALPHA, ALPHA, 
  TS_8b_Black, TS_8b_White, TS_8b_White, TS_8b_White, TS_8b_White, TS_8b_Black, TS_8b_White, TS_8b_White, TS_8b_Black, TS_8b_White, TS_8b_White, TS_8b_White, TS_8b_White, TS_8b_Black, ALPHA, ALPHA, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_White, TS_8b_White, TS_8b_Black, TS_8b_White, TS_8b_White, TS_8b_Black, TS_8b_White, TS_8b_White, TS_8b_Black, TS_8b_Black, ALPHA, ALPHA, ALPHA, 
  TS_8b_Black, TS_8b_White, TS_8b_Black, TS_8b_Black, TS_8b_White, TS_8b_White, TS_8b_Red, TS_8b_Red, TS_8b_White, TS_8b_White, TS_8b_Black, TS_8b_Red, TS_8b_Black, ALPHA, ALPHA, ALPHA, ALPHA, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_White, TS_8b_Black, ALPHA, ALPHA, ALPHA, 
  ALPHA, ALPHA, TS_8b_Black, TS_8b_Black, TS_8b_Red, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_White, TS_8b_White, TS_8b_Black, TS_8b_Black, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, TS_8b_Black, TS_8b_Black, TS_8b_Black, TS_8b_Red, TS_8b_Red, TS_8b_Black, TS_8b_White, TS_8b_White, TS_8b_Black, ALPHA, ALPHA, ALPHA, ALPHA, 
  ALPHA, ALPHA, ALPHA, TS_8b_Black, TS_8b_Red, TS_8b_Red, TS_8b_Black, TS_8b_Black, ALPHA, TS_8b_Black, TS_8b_Black, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, TS_8b_Black, TS_8b_Black, TS_8b_Black, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA, ALPHA
};